import React from 'react';
import Head from 'next/head';
import Header from './Header';
import Footer from './Footer';

export const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>CHIOMA OTU - FRONTEND DEVELOPER</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>{children}</main>

      <Footer />
    </>
  );
};
